### ISSUE TITLE
livekit-cli load-test failing with panic

### ISSUE THREAD

**Issue by sequ3l** [livekit/livekit-cli#84] opened 2022-08-29 19:56 UTC
When attempting to load test, I get the follow output when video is involved. Audio only works fine.
```
> livekit-cli load-test --url <url> --room load-test --publishers 1 --subscribers 1 --video-resolution low --audio-bitrate 45000 --api-key <apiKey> --api-secret <apiSecret> --video-codec h264 --duration 1m

Starting load test with 1 publishers, 1 subscribers, room: load-test
panic: non-positive interval for Ticker.Reset
```
I did set the relevant variables for load-testing:
```
ulimit -n 65535
sysctl -w fs.file-max=2097152
sysctl -w net.core.somaxconn=65535
sysctl -w net.core.rmem_max=25165824
sysctl -w net.core.wmem_max=2516582
```

**Comment by davidzhao** [comment] 2022-08-31 16:14
@sequ3l, is there a stack trace with that panic log as well? I'm not able to reproduce the panic using the args that you provided.

**Comment by sequ3l** [comment] 2022-08-31 16:24
@davidzhao, here's the stack trace:

```
goroutine 154 [running]:
time.(*Ticker).Reset(0xc0bc00a256d231f4?, 0x9545e88d?)
        /opt/hostedtoolcache/go/1.18.4/x64/src/time/tick.go:55 +0x8f
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc00036e1a0, {0x1c2e5260440, 0xc0002d8cc0}, 0x0)
        /home/runner/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220713082711-d564d99d80b2/localsampletrack.go:422 +0x3a9
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
        /home/runner/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220713082711-d564d99d80b2/localsampletrack.go:185 +0x57b
panic: non-positive interval for Ticker.Reset

goroutine 94 [running]:
time.(*Ticker).Reset(0xc0bc00a256d231f4?, 0x9545e88d?)
        /opt/hostedtoolcache/go/1.18.4/x64/src/time/tick.go:55 +0x8f
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc00036e340, {0x1c2e5260440, 0xc0002d8d50}, 0x0)
        /home/runner/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220713082711-d564d99d80b2/localsampletrack.go:422 +0x3a9
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
        /home/runner/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220713082711-d564d99d80b2/localsampletrack.go:185 +0x57b
```

**Comment by davidzhao** [comment] 2022-09-01 20:21
This should be fixed in 1.1.1, give it a shot and let me know if it works for you.

**Comment by sequ3l** [comment] 2022-09-01 21:04
@davidzhao, thank you for your effort, it's working impressively well!

**Comment by davidzhao** [comment] 2022-09-02 01:09
awesome! thank you for confirming. closing the issue.

**Closed by davidzhao** 2022-09-02 01:09 UTC
