### ISSUE TITLE
Python 3.13 - livekit-plugins-openai pip install failure

### ISSUE THREAD

**Issue by joshmoose** [livekit/livekit-cli#457] opened 2024-10-30 04:30 UTC
Following instructions to set up multimodal python app. 

Correctly created and sourced  venv.
At pip install -r requirements.txt:

Collecting pillow~=10.3.0 (from livekit-agents[codecs,images]>=0.8.0.dev0->livekit-plugins-openai~=0.10.3->-r requirements.txt (line 3))
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1

Remedial actions:
Create venv manually downgraded with: 

python3.12 -m venv venv

System:
Mac OS 14.6.1
Python 3.13.0

**Comment by davidzhao** [comment] 2024-10-30 07:02
Python 3.13 is not supported yet, dupe of https://github.com/livekit/agents/issues/933

**Closed by davidzhao** 2024-10-30 07:02 UTC
